### PR TITLE
Adding figure 3

### PR DESCRIPTION
**Pull request by dvenprasad**
Added: pdf, svg, and png formats

### Purpose
https://github.com/jaybee84/ml-in-rd/issues/180

### Manuscript checklist

Unless otherwise noted above, this PR will be considered ready for review when all four items have been checked.

- [ ] All changes to text follow "one sentence per line" [[Manubot instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#manubot-markdown)]
- [ ] All citations follow the [Manubot citation instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#citations)
- [ ] All changes or additions to tables follow the [Manubot table instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#tables)
- [ ] All figures follow the [Manubot figure instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#figures)
- [ ] All terms that need to be added to glossary have been added to #50 
- [ ] There are no new spelling errors identified by the Manubot spellchecker

### CODE REVIEW

**Comment by jaybee84** [comment]
@dvenprasad the EHR icon looks a bit small compared to the other components. Would it be possible to scale it to match the size of the other components?

Also, maybe align the right margin of all the panels so that they all align (kind of like "justify" in a word doc ) :)

**Comment by dvenprasad** [comment]
Yep, made those changes :)

**Review by jaybee84 — COMMENTED** [review]
@dvenprasad Thanks for enlarging EHR icon. The right side of all the panels are still not aligned. Was that intentional?

**Comment by jaybee84** [comment]
@dvenprasad just checking with you about the above comment

**Comment by dvenprasad** [comment]
Oh I see that you say right aligned! (I've been reading it as left align all this while 🤦‍♀️ ) 
Yeah the items not aligning on right is a function of how much real estate each of the steps take. I am hesitant to stretch out the arrows or space between the steps just to line them up on the right because it would just add extra space and the other panels look weird. It would kinda look like justifying on word with only a few words on a line.

**Pull request merged**
