### PR TITLE
enable docx build

### PR DESCRIPTION
**Pull request by cgreene**
### Purpose

Enable DOCX build

#### Which areas should receive a particularly close look?

Is there a docx?

### Manuscript checklist

Unless otherwise noted above, this PR will be considered ready for review when all four items have been checked.

- [ ] All changes to text follow "one sentence per line" [[Manubot instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#manubot-markdown)]
- [ ] All citations follow the [Manubot citation instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#citations)
- [ ] All changes or additions to tables follow the [Manubot table instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#tables)
- [ ] All figures follow the [Manubot figure instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#figures)
- [ ] All terms that need to be added to glossary have been added to #50 
- [ ] There are no new spelling errors identified by the Manubot spellchecker

### CODE REVIEW

**Comment by cgreene** [comment]
Confirmed - docx here: https://github.com/jaybee84/ml-in-rd/suites/1439496457/artifacts/24377621

**Review by jaybee84 — APPROVED** [review]

**Comment by jaybee84** [comment]
Thanks @cgreene ! What is the best way to access the zip folder you mentioned above for PR merges going forward?

**Comment by cgreene** [comment]
It'll end up on the output branch from here on out. You should find it there as soon as this merge builds 😁

**Comment by jaybee84** [comment]
@cgreene I dont see it on the draft-branch or the main branch (output branches) yet.. Do we need to do add/change something in the config?

**Pull request merged**
