### PR TITLE
Added 3. figures

### PR DESCRIPTION
**Pull request by dvenprasad**
Added
- statistical techniques
- dimensionality reduction
- multiplier and deep profile

### Purpose

For #106 #116 #108 

#### Which areas should receive a particularly close look?
- I iterated over the feedback for dimensionality reduction. Did I get the new feature plot correct?
- How does the layout for bootstrapping, ensemble learning, regularization, and one class at a time look?
EDIT (1/21) : I added the last set of figures. I could use feedback on Multitask learning and knowledge graph figures

#### Is the pull request ready for review?
yes

### Manuscript checklist

Unless otherwise noted above, this PR will be considered ready for review when all four items have been checked.

- [ ] All changes to text follow "one sentence per line" [[Manubot instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#manubot-markdown)]
- [ ] All citations follow the [Manubot citation instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#citations)
- [ ] All changes or additions to tables follow the [Manubot table instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#tables)
- [ ] All figures follow the [Manubot figure instructions](https://github.com/jaybee84/ml-in-rd/blob/draft-branch/USAGE.md#figures)
- [ ] All terms that need to be added to glossary have been added to #50 
- [ ] There are no new spelling errors identified by the Manubot spellchecker

### CODE REVIEW

**Review by jaclyn-taroni — COMMENTED** [review]
These look good to me! I am looking forward to taking another pass through the manuscript to make sure these are integrated nicely into the main text.

**Comment by dvenprasad** [comment]
I had a question, for the figures with multiple sub-figures, should we add `A.<title>` B.<title>` so it is easier to refer to them while writing/reading?

**Comment by jaclyn-taroni** [comment]
> I had a question, for the figures with multiple sub-figures, should we add `A.<title>` B.<title>` so it is easier to refer to them while writing/reading?

I think we should add lettering to the panels, e.g., `A` and `B`, and we will need to number the figures to refer to them in the text. Any titles should come in the figure legends in my opinion.

**Comment by dvenprasad** [comment]
Ah I see. 
To clarify, for example in the transfer learning panel, we would replace the title `Transfer Learning` with `A` ?

Screen Shot 2021-01-21 at 2 27 55 PM

**Comment by jaclyn-taroni** [comment]
Ah, I see what you mean by title. I think it's fine to leave `Transfer Learning` in in that case, but I would add `A` separately (probably larger and in a different font).

**Comment by dvenprasad** [comment]
Okay. phew! I was very very confused. Okay, will add those in.

**Review by jaybee84 — CHANGES_REQUESTED** [review]
Thanks for putting the figures together. Overall they look great! Few suggestions:

1. Can the text font be increased? I tried to shrink the images down to figure panel level (1/4 of a page or 1/3 of a page) and that affected the readability of the text.
2. The figures currently have a lot of white space, is it possible to reduce it?
3. the prior knowledge section text sequence is knowledge graph, transfer learning, multitask and few-shot learning.. so maybe we can keep the same sequence in the figure. Also, compartmentalizing each panel may make the figure a bit more put together :)
4. The "light bulbs" as an icon for overarching concepts should probably be restricted to multiplier-Deepprofile figure only since this will be the "putting it all together" figure.

**Comment by jaybee84** [comment]
@jaybee84 to look up figure requirements in the target journal

**Comment by jaybee84** [comment]
The guidelines for dimensions of figures are as follows:

```All panels of a figure or table (for example, Fig. 1a, b and c) should be combined into one file; please do not send as separate files. Image files should be just large enough to view when the screen resolution is set to 640 x 480 pixels. Remember to include a brief title and legend (preferably incorporated into the image file to appear near the image) as part of every electronic figure submitted, and a title as part of every table.```

For more details see #90

**Comment by dvenprasad** [comment]
- added a. <title> on panels
- adjusted to figure specifications
- moved figures to image directory
- added pdfs and tiffs of the figures
- addressed comments on PR.

The ensemble learning panel is still a bit iffy when resized. I'm not sure what we can do without modifying the figure somewhat

**Review by jaybee84 — APPROVED** [review]
@dvenprasad I added a few minor edits, let me know if you absolutely hate them :)

Otherwise looks good.

**Comment by dvenprasad** [comment]
Personally I am okay with the grey boxes but I added lines because of this figure guideline

> All display items should be on a white background, and should avoid excessive boxing, unnecessary colour, spurious decorative effects

I interpreted this to mean white background for all panels and the figure itself. Maybe I misinterpreted?

**Comment by jaybee84** [comment]
Ah! got it... you probably interpreted it correctly...  we can pick up on this during our round robins :)

**Pull request merged**
