### PR TITLE
Move deploy logic in GitHub Actions workflow

### PR DESCRIPTION
**Pull request by agitter**
### Purpose

This begins to address the desire to deploy from `master` and/or `draft-branch`. The initial commit moves the deploy logic from the `if` statement in the workflow to the `run`  block.  In the `run` block, you can use standard bash script syntax to have full control over deploy conditions, such as the branch (ref). 
 See
- https://github.com/jaybee84/ml-in-rd/issues/17
- https://github.com/manubot/rootstock/issues/341#issuecomment-632932132

#### Which areas should receive a particularly close look?
The GitHub Actions log (nevermind, the deploy step does not run in a pull request, as noted below)

#### Is there anything that you want to discuss further?
Depends on whether the new logic works or fails.  This is not a complete implementation of deploying from multiple branches, but if it works you'll be able to modify it further.

#### Is the pull request ready for review?
Yes

### CODE REVIEW

**Comment by agitter** [comment]
The "Deploy Manuscript" step is skipped in this pull request because the `!github.event.repository.fork` condition fails.  You may need to merge and continue playing with this structure to get it to work.

**Review by jaybee84 — APPROVED** [review]

**Comment by agitter** [comment]
The deploy step ran as intended.  This line in the build log indicates one more change may be needed: https://github.com/jaybee84/ml-in-rd/runs/707633213#step:8:19

The deploy script is checking out the master branch instead of the branch the pull request was merged to:
https://github.com/jaybee84/ml-in-rd/blob/808343dd9dc459d00413c4091501a9d4d0f5c902/ci/deploy.sh#L15

As a next step, you could try replacing `TRAVIS_BRANCH` in that deploy script line with `GITHUB_REF`, which is now set in the GitHub Actions workflow.

**Comment by jaybee84** [comment]
Thanks @agitter ! This worked perfectly and now the output gh-pages on draft-branch is pointing to the  draft-branch content.

A small caveat, with this change the gh-pages on master and draft-branch are both pointing to the draft-branch content. I tried updating the master branch deploy.sh to keep pointing to the master branch so that the output gh-pages on master branch keeps pointing to master branch content (which is a few commits behind the draft-branch). But that made both draft-branch and master branch point to the master branch content (which is not desirable).

I was trying to make the draft-branch gh-pages work as a staging site, while the master gh-pages show the production-ready version, but maybe there needs to be additional logic to make that happen.

**Comment by agitter** [comment]
`gh-pages` is a git branch, and there is only one such branch per repository.  If `master` and `draft-branch` could each have their own "pages" branch, I understand your intended workflow better.  However, that isn't what GitHub supports.  The repository settings will determine what to render at https://jaybee84.github.io/ml-in-rd/ but it is always coming from the same location or branch.

Because Manubot versions each deployed manuscript (https://github.com/jaybee84/ml-in-rd/tree/gh-pages/v) it may be possible to edit the Manubot Python package to point different URLs to different versions of the deployed manuscript.  However, that would require a lot of development work.

There may be some workaround where you would run `deploy.sh` twice in each deploy step, once using `draft-branch` and again using `master`.  This would be wasteful and clutter the commit history.  However, it may have the effect of creating a new versioned manuscript in https://github.com/jaybee84/ml-in-rd/tree/gh-pages/v while still keeping https://jaybee84.github.io/ml-in-rd/ pointed at the version build from the `master` branch.

I can't fully anticipate how that would work.  If you want to test it, modify these lines
https://github.com/jaybee84/ml-in-rd/blob/ffe9862537c38b96b5097371ebc3efe6b1fe2634/.github/workflows/manubot.yaml#L63-L65
to
```
           if [ "$GITHUB_REF" = "refs/heads/draft-branch" ]; then 
             # generate the versioned web page for the draft-branch content
             bash ci/deploy.sh
             # re-generate and re-deploy the versioned web page for the master content
             # so that https://jaybee84.github.io/ml-in-rd/ shows the master branch version
             GITHUB_REF=master
             bash ci/deploy.sh 
           fi 
```
and see if the new behavior is better or worse.  You would have to manually look up the permalink with the commit id for the version of the manuscript that was deployed from the `draft-branch` content.

**Comment by jaybee84** [comment]
Thanks @agitter. Somehow I missed the last comment in the thread. I will try your suggested edits and keep you posted. 

Thanks again for your help with this!

**Pull request merged**
