### PR TITLE
adding draft-branch to power gh-pages

### PR DESCRIPTION
**Pull request by jaybee84**
### Purpose

#17 

#### Is there anything that you want to discuss further?

None
#### Is the pull request ready for review?
Yes

### CODE REVIEW

**Comment by cgreene** [comment]
I missed this PR. What was the goal of this? This is not, to my knowledge, necessary to get gh-pages working.

**Comment by cgreene** [comment]
See 
> GitHub Pages deployment using GITHUB_TOKEN recently started working on GitHub without an official announcement. If it does not work for you after completing this setup, try reselecting "gh-pages branch" as the Source for GitHub Pages in the repository Settings. GitHub Pages should now trigger on the next commit. 

in https://github.com/jaybee84/ml-in-rd/blob/draft-branch/SETUP.md#github-actions

**Comment by cgreene** [comment]
If you want to mark me as an admin on this repo I can finish setting it up if you want gh-pages

**Comment by jaybee84** [comment]
@cgreene This PR was intended to configure the yaml such that the gh-pages can be powered by the draft-branch instead of the master branch. 

But changing the yaml to point to draft-branch instead of master did not fix the issue.

From recent conversations with agitter, it seems that the GH Actions artifact may be sufficient as a solution we need to visualize the draft-branch when a PR is generated against it.

**Comment by jaybee84** [comment]
Adding you as an admin to the repo ... would greatly appreciate any help in setting up  :)

**Comment by jaybee84** [comment]
hmm... interesting... since this is repo is in my personal user account, I am not being able to change your  access permission from collaborator to admin from settings..  is there a different way to do this?

**Pull request merged**
