### PR TITLE
Fix spellcheck errors

### PR DESCRIPTION
**Pull request by jaclyn-taroni**
### Purpose

We have spellcheck via AppVeyor, but don't yet have instructions for how to resolve or work with spellcheck. Here I'm adding things to the custom dictionary related to #44. Note that the vast majority of the changes showing up in the diff are the result of merging `origin/draft-branch`. I am just adding terms to `build/assets/custom-dictionary.txt`.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
Probably should have explicitly pointed out that the base branch here is https://github.com/jaybee84/ml-in-rd/tree/allaway/heterogenity, with the idea if this gets merged those changes will show up on #44.

**Comment by allaway** [comment]
Oh no! I didn't see this in time before merging #44. Should we change this to merge into `draft-branch`?

**Comment by jaclyn-taroni** [comment]
Sure let's give that a try!

**Comment by jaclyn-taroni** [comment]
Side note: Is being able to change the base branch after initial filing a new feature? 🤔 I thought that was not allowed in the past...

**Comment by jaclyn-taroni** [comment]
I think I'm going to close this, no big deal!

**Comment by allaway** [comment]
Looking at the diff, I think this can be merged as-is to `draft-branch` now, unless I'm missing something.

**Review by allaway — COMMENTED** [review]
LGTM!

**Review by allaway — APPROVED** [review]
I added one line with "pre". Feel free to merge if this is OK!

**Comment by allaway** [comment]
The manuscript build failed, it rejected the dash in `t-SNE` in the dictionary. I split this up into two words (`t` and `SNE`). hopefully this works.

**Pull request merged**
